#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

_requirements() {
  local \
    _os
  _os="$( \
    uname \
      -o)"
  if [[ "${_os}" == 'Android' ]]; then
    _check_cmd \
      "activity-launch" \
      "android-activity-utils"
  fi
}

# shellcheck disable=SC2034
_global_variables() {
  view_date=""
  view_length=""
  poll_interval=""
  camera_app=""
  display_dim=""
  touch_disabled=""
  color=""
  quiet=""
}

_android_camera() {
  local \
    _duration="${1}" \
    _app="${2}" \
    _poll="${3}" \
    _dim="${4}" \
    _touch_disabled="${5}" \
    _activity_launch_opts=() \
    _opts=() \
    _conf
  shift \
    5
  _opts=(
    "$@"
  )
  _conf="$( \
    _get_conf_path)"
  if [[ "${quiet}" != "y" ]]; then
    _activity_launch_opts+=(
     -v
    )
  fi
  if (( 0 < "${_duration}" )); then
    _activity_launch_opts+=(
     -L
       "${_duration}"
     -p
       "${_poll}"
    )
  fi
  if [[ "${_dim}" == "y" ]]; then
    _activity_launch_opts+=(
     -d
    )
  fi
  if [[ "${_touch_disabled}" == "y" ]]; then
    _activity_launch_opts+=(
     -t
    )
  fi
  activity-launch \
    "${_activity_launch_opts[@]}" \
    "${_app}" \
    "MainActivity" 
}

_camera_app_auto_detect() {
  local \
    _os
  _os="$( \
    uname \
      -o)"
  if [[ "${_os}" == 'Android' ]]; then
    echo \
      'net.sourceforge.opencamera'
  fi
}

_get_conf_path() {
  local \
    _dir \
    _conf
  _dir="${HOME}/.config/android-camera"
  _conf="${_dir}/$( \
    _get \
      "app" \
      "name").cfg"
  echo \
    "${_conf}"
}

_set_overrides() {
  _set_override \
    "view" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "view" \
    "length" \
    "$(( 10 * 60 ))" # 10 minutes
    # "$(( 60 * 60 * 24 ))" # 24 hours
  _set_override \
    "camera" \
    "app" \
    "$(_camera_app_auto_detect)"
  _set_override \
    "poll" \
    "interval" \
    "30"
  _set_override \
    "display" \
    "dim" \
    "n"
  _set_override \
    "touch" \
    "disabled" \
    "n"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                View date:   $(_get "view" "date")"
  _msg_info "            Poll interval:   $(_get "poll" "interval")"
  _msg_info "               Camera app:   $(_get "camera" "app")"
  _msg_info "              Display dim:   $(_get "display" "dim")"
  _msg_info "           Touch disabled:   $(_get "touch" "disabled")"
  _msg_info "              View length:   $(_get "view" "length")"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Start an android camera for a while.

Usage:
  $(_get "app" "name")
    [options]
  options:
     -L <view_length>     View length in seconds.
			  Default: $(_get "view" "length")
     -a <camera_app>      Your Android camera app.
			  Default: $(_get "camera" "app")
     -d                   Whether to dim the screen or not.
     -t                   Whether to disable touch or not.
     -p                   Poll interval for brightness and
                          touch reset in seconds.
			  Default: $(_get "poll" "interval")
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'L:a:p:dtcvh?' \
    arg; do
  case \
    "${arg}" in
    L) override_view_length="${OPTARG}" ;;
    a) override_camera_app="${OPTARG}" ;;
    p) override_poll_interval="${OPTARG}" ;;
    d) override_display_dim="y" ;;
    t) override_touch_disabled="y" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
	 _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0 && \
    _set_overrides && \
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
_set_overrides
_config_user_init \
  "$(_get 'app' 'name')"
app_opts=(
  "$(_get \
       "view" \
       "length")"
  "$(_get \
       "camera" \
       "app")"
  "$(_get \
       "poll" \
       "interval")"
  "$(_get \
       "display" \
       "dim")"
  "$(_get \
       "touch" \
       "disabled")"
)
_show_config
_android_camera \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
