#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
	 "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

_requirements() {
  local \
    _os
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == 'Android' ]]; then
    _check_cmd \
      "activity-launch" \
      "android-activity-utils"
  fi
}

# shellcheck disable=SC2034
_global_variables() {
  view_date=""
  view_length=""
  poll_interval=""
  camera_app=""
  display_dim=""
  touch_disabled=""
  color=""
  quiet=""
}

_android_camera() {
  local \
    _duration="${1}" \
    _app="${2}" \
    _poll="${3}" \
    _dim="${4}" \
    _touch_disabled="${5}" \
    _activity_launch_opts=() \
    _opts=() \
    _conf
  shift \
    5
  _opts=(
    "$@"
  )
  _conf="$(
    _get_conf_path)"
  if [[ "${quiet}" != "y" ]]; then
    _activity_launch_opts+=(
     -v
    )
  fi
  if (( 0 < "${_duration}" )); then
    _activity_launch_opts+=(
     -L
       "${_duration}"
     -p
       "${_poll}"
    )
  fi
  if [[ "${_dim}" == "y" ]]; then
    _activity_launch_opts+=(
     -d
    )
  fi
  if [[ "${_touch_disabled}" == "y" ]]; then
    _activity_launch_opts+=(
     -t
    )
  fi
  activity-launch \
    "${_activity_launch_opts[@]}" \
    "${_app}" \
    "MainActivity" 
}

_camera_app_auto_detect() {
  local \
    _os
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == 'Android' ]]; then
    echo \
      'net.sourceforge.opencamera'
  fi
}

_get_conf_path() {
  local \
    _dir \
    _conf
  _dir="${HOME}/.config/android-camera"
  _conf="${_dir}/${app_name}.cfg"
  echo \
    "${_conf}"
}

_set_overrides() {
  _set_override \
    "view" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "view" \
    "length" \
    "$(( 10 * 60 ))" # 10 minutes
    # "$(( 60 * 60 * 24 ))" # 24 hours
  _set_override \
    "camera" \
    "app" \
    "$(_camera_app_auto_detect)"
  _set_override \
    "poll" \
    "interval" \
    "30"
  _set_override \
    "display" \
    "dim" \
    "n"
  _set_override \
    "touch" \
    "disabled" \
    "n"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                View date:   ${view_date}"
  _msg_info "            Poll interval:   ${poll_interval}"
  _msg_info "               Camera app:   ${camera_app}"
  _msg_info "              Display dim:   ${display_dim}"
  _msg_info "           Touch disabled:   ${touch_disabled}"
  _msg_info "              View length:   ${view_length}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Start an android camera for a while.

Usage:
  ${app_name}
    [options]
  options:
     -L <view_length>     View length in seconds.
			  Default: ${view_length}
     -a <camera_app>      Your Android camera app.
			  Default: ${camera_app}
     -d                   Whether to dim the screen or not.
     -t                   Whether to disable touch or not.
     -p                   Poll interval for brightness and
                          touch reset in seconds.
			  Default: ${poll_interval}
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'L:a:p:dtcvh?' \
    arg; do
  case \
    "${arg}" in
    L) override_view_length="${OPTARG}" ;;
    a) override_camera_app="${OPTARG}" ;;
    p) override_poll_interval="${OPTARG}" ;;
    d) override_display_dim="y" ;;
    t) override_touch_disabled="y" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
	 _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0 && \
    _set_overrides && \
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
_set_overrides
_config_user_init \
  "${app_name}"
app_opts=(
  "${view_length}"
  "${camera_app}"
  "${poll_interval}"
  "${display_dim}"
  "${touch_disabled}"
)
_show_config
_android_camera \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
